name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
              cd ~/live-chat-app/live-chat-client
              git fetch origin main
              git reset --hard origin/main
              npm install
              npm run build
              sudo chown -R ubuntu:ubuntu /var/www/livechat/dist
              sudo cp -r dist/* /var/www/livechat/dist/
              sudo chown -R www-data:www-data /var/www/livechat/dist
              sudo systemctl reload nginx